// Generated by scripts/optimize-galleries.js — do not edit by hand
window.GALLERIES = {
 "aaathma": {
  "name": "Aaathma",
  "images": [
   "images/gallery/aaathma/01.jpg",
   "images/gallery/aaathma/02.jpg",
   "images/gallery/aaathma/03.jpg",
   "images/gallery/aaathma/04.jpg",
   "images/gallery/aaathma/05.jpg",
   "images/gallery/aaathma/06.jpg",
   "images/gallery/aaathma/07.jpg",
   "images/gallery/aaathma/08.jpg",
   "images/gallery/aaathma/09.jpg",
   "images/gallery/aaathma/10.jpg",
   "images/gallery/aaathma/11.jpg",
   "images/gallery/aaathma/12.jpg",
   "images/gallery/aaathma/13.jpg",
   "images/gallery/aaathma/14.jpg",
   "images/gallery/aaathma/15.jpg",
   "images/gallery/aaathma/16.jpg",
   "images/gallery/aaathma/17.jpg",
   "images/gallery/aaathma/18.jpg"
  ]
 },
 "armitage-hill-galle": {
  "name": "Armitage Hill Galle",
  "images": [
   "images/gallery/armitage-hill-galle/01.jpg",
   "images/gallery/armitage-hill-galle/02.jpg",
   "images/gallery/armitage-hill-galle/03.jpg",
   "images/gallery/armitage-hill-galle/04.jpg",
   "images/gallery/armitage-hill-galle/05.jpg",
   "images/gallery/armitage-hill-galle/06.jpg",
   "images/gallery/armitage-hill-galle/07.jpg",
   "images/gallery/armitage-hill-galle/08.jpg",
   "images/gallery/armitage-hill-galle/09.jpg",
   "images/gallery/armitage-hill-galle/10.jpg",
   "images/gallery/armitage-hill-galle/11.jpg",
   "images/gallery/armitage-hill-galle/12.jpg",
   "images/gallery/armitage-hill-galle/13.jpg",
   "images/gallery/armitage-hill-galle/14.jpg",
   "images/gallery/armitage-hill-galle/15.jpg"
  ]
 },
 "artotel-sanur": {
  "name": "Artotel Sanur",
  "images": [
   "images/gallery/artotel-sanur/01.jpg",
   "images/gallery/artotel-sanur/02.jpg",
   "images/gallery/artotel-sanur/03.jpg",
   "images/gallery/artotel-sanur/04.jpg",
   "images/gallery/artotel-sanur/05.jpg",
   "images/gallery/artotel-sanur/06.jpg"
  ]
 },
 "ayr-castle": {
  "name": "Ayr Castle",
  "images": [
   "images/gallery/ayr-castle/01.jpg",
   "images/gallery/ayr-castle/02.jpg",
   "images/gallery/ayr-castle/03.jpg",
   "images/gallery/ayr-castle/04.jpg",
   "images/gallery/ayr-castle/05.jpg",
   "images/gallery/ayr-castle/06.jpg",
   "images/gallery/ayr-castle/07.jpg",
   "images/gallery/ayr-castle/08.jpg",
   "images/gallery/ayr-castle/09.jpg",
   "images/gallery/ayr-castle/10.jpg",
   "images/gallery/ayr-castle/11.jpg",
   "images/gallery/ayr-castle/12.jpg",
   "images/gallery/ayr-castle/13.jpg",
   "images/gallery/ayr-castle/14.jpg",
   "images/gallery/ayr-castle/15.jpg"
  ]
 },
 "cape-waligama": {
  "name": "Cape Waligama",
  "images": [
   "images/gallery/cape-waligama/01.jpg",
   "images/gallery/cape-waligama/02.jpg",
   "images/gallery/cape-waligama/03.jpg",
   "images/gallery/cape-waligama/04.jpg",
   "images/gallery/cape-waligama/05.jpg",
   "images/gallery/cape-waligama/06.jpg",
   "images/gallery/cape-waligama/07.jpg",
   "images/gallery/cape-waligama/08.jpg",
   "images/gallery/cape-waligama/09.jpg",
   "images/gallery/cape-waligama/10.jpg",
   "images/gallery/cape-waligama/11.jpg"
  ]
 },
 "helios-boutique-villa": {
  "name": "Helios Boutique Villa",
  "images": [
   "images/gallery/helios-boutique-villa/01.jpg",
   "images/gallery/helios-boutique-villa/02.jpg",
   "images/gallery/helios-boutique-villa/03.jpg",
   "images/gallery/helios-boutique-villa/04.jpg",
   "images/gallery/helios-boutique-villa/05.jpg",
   "images/gallery/helios-boutique-villa/06.jpg",
   "images/gallery/helios-boutique-villa/07.jpg",
   "images/gallery/helios-boutique-villa/08.jpg",
   "images/gallery/helios-boutique-villa/09.jpg",
   "images/gallery/helios-boutique-villa/10.jpg",
   "images/gallery/helios-boutique-villa/11.jpg",
   "images/gallery/helios-boutique-villa/12.jpg",
   "images/gallery/helios-boutique-villa/13.jpg",
   "images/gallery/helios-boutique-villa/14.jpg",
   "images/gallery/helios-boutique-villa/15.jpg"
  ]
 },
 "kalkudah-beach-house": {
  "name": "Kalkudah Beach House",
  "images": [
   "images/gallery/kalkudah-beach-house/01.jpg",
   "images/gallery/kalkudah-beach-house/02.jpg",
   "images/gallery/kalkudah-beach-house/03.jpg",
   "images/gallery/kalkudah-beach-house/04.jpg",
   "images/gallery/kalkudah-beach-house/05.jpg",
   "images/gallery/kalkudah-beach-house/06.jpg",
   "images/gallery/kalkudah-beach-house/07.jpg",
   "images/gallery/kalkudah-beach-house/08.jpg",
   "images/gallery/kalkudah-beach-house/09.jpg",
   "images/gallery/kalkudah-beach-house/10.jpg",
   "images/gallery/kalkudah-beach-house/11.jpg",
   "images/gallery/kalkudah-beach-house/12.jpg",
   "images/gallery/kalkudah-beach-house/13.jpg",
   "images/gallery/kalkudah-beach-house/14.jpg",
   "images/gallery/kalkudah-beach-house/15.jpg",
   "images/gallery/kalkudah-beach-house/16.jpg",
   "images/gallery/kalkudah-beach-house/17.jpg",
   "images/gallery/kalkudah-beach-house/18.jpg",
   "images/gallery/kalkudah-beach-house/19.jpg",
   "images/gallery/kalkudah-beach-house/20.jpg",
   "images/gallery/kalkudah-beach-house/21.jpg",
   "images/gallery/kalkudah-beach-house/22.jpg",
   "images/gallery/kalkudah-beach-house/23.jpg",
   "images/gallery/kalkudah-beach-house/24.jpg",
   "images/gallery/kalkudah-beach-house/25.jpg",
   "images/gallery/kalkudah-beach-house/26.jpg",
   "images/gallery/kalkudah-beach-house/27.jpg"
  ]
 },
 "landesi-galle": {
  "name": "Landesi Galle",
  "images": [
   "images/gallery/landesi-galle/01.jpg",
   "images/gallery/landesi-galle/02.jpg",
   "images/gallery/landesi-galle/03.jpg",
   "images/gallery/landesi-galle/04.jpg",
   "images/gallery/landesi-galle/05.jpg",
   "images/gallery/landesi-galle/06.jpg",
   "images/gallery/landesi-galle/07.jpg",
   "images/gallery/landesi-galle/08.jpg",
   "images/gallery/landesi-galle/09.jpg",
   "images/gallery/landesi-galle/10.jpg"
  ]
 },
 "le-grand-galle": {
  "name": "Le Grand Galle",
  "images": [
   "images/gallery/le-grand-galle/01.jpg",
   "images/gallery/le-grand-galle/02.jpg",
   "images/gallery/le-grand-galle/03.jpg",
   "images/gallery/le-grand-galle/04.jpg",
   "images/gallery/le-grand-galle/05.jpg",
   "images/gallery/le-grand-galle/06.jpg",
   "images/gallery/le-grand-galle/07.jpg"
  ]
 },
 "leela-walauwwa": {
  "name": "Leela Walauwwa",
  "images": [
   "images/gallery/leela-walauwwa/01.jpg",
   "images/gallery/leela-walauwwa/02.jpg",
   "images/gallery/leela-walauwwa/03.jpg",
   "images/gallery/leela-walauwwa/04.jpg",
   "images/gallery/leela-walauwwa/05.jpg",
   "images/gallery/leela-walauwwa/06.jpg",
   "images/gallery/leela-walauwwa/07.jpg",
   "images/gallery/leela-walauwwa/08.jpg",
   "images/gallery/leela-walauwwa/09.jpg"
  ]
 },
 "mayur-lodge": {
  "name": "Mayur Lodge",
  "images": [
   "images/gallery/mayur-lodge/01.jpg",
   "images/gallery/mayur-lodge/02.jpg",
   "images/gallery/mayur-lodge/03.jpg",
   "images/gallery/mayur-lodge/04.jpg",
   "images/gallery/mayur-lodge/05.jpg",
   "images/gallery/mayur-lodge/06.jpg",
   "images/gallery/mayur-lodge/07.jpg",
   "images/gallery/mayur-lodge/08.jpg",
   "images/gallery/mayur-lodge/09.jpg",
   "images/gallery/mayur-lodge/10.jpg",
   "images/gallery/mayur-lodge/11.jpg"
  ]
 },
 "nine-skies": {
  "name": "Nine Skies",
  "images": [
   "images/gallery/nine-skies/01.jpg",
   "images/gallery/nine-skies/02.jpg",
   "images/gallery/nine-skies/03.jpg",
   "images/gallery/nine-skies/04.jpg",
   "images/gallery/nine-skies/05.jpg",
   "images/gallery/nine-skies/06.jpg",
   "images/gallery/nine-skies/07.jpg",
   "images/gallery/nine-skies/08.jpg",
   "images/gallery/nine-skies/09.jpg",
   "images/gallery/nine-skies/10.jpg",
   "images/gallery/nine-skies/11.jpg",
   "images/gallery/nine-skies/12.jpg",
   "images/gallery/nine-skies/13.jpg",
   "images/gallery/nine-skies/14.jpg",
   "images/gallery/nine-skies/15.jpg",
   "images/gallery/nine-skies/16.jpg",
   "images/gallery/nine-skies/17.jpg",
   "images/gallery/nine-skies/18.jpg"
  ]
 },
 "on-the-rocks": {
  "name": "On The Rocks",
  "images": [
   "images/gallery/on-the-rocks/01.jpg",
   "images/gallery/on-the-rocks/02.jpg",
   "images/gallery/on-the-rocks/03.jpg",
   "images/gallery/on-the-rocks/04.jpg",
   "images/gallery/on-the-rocks/05.jpg",
   "images/gallery/on-the-rocks/06.jpg"
  ]
 },
 "rock-villa": {
  "name": "Rock Villa",
  "images": [
   "images/gallery/rock-villa/01.jpg",
   "images/gallery/rock-villa/02.jpg",
   "images/gallery/rock-villa/03.jpg",
   "images/gallery/rock-villa/04.jpg",
   "images/gallery/rock-villa/05.jpg",
   "images/gallery/rock-villa/06.jpg",
   "images/gallery/rock-villa/07.jpg",
   "images/gallery/rock-villa/08.jpg",
   "images/gallery/rock-villa/09.jpg",
   "images/gallery/rock-villa/10.jpg",
   "images/gallery/rock-villa/11.jpg",
   "images/gallery/rock-villa/12.jpg",
   "images/gallery/rock-villa/13.jpg",
   "images/gallery/rock-villa/14.jpg",
   "images/gallery/rock-villa/15.jpg",
   "images/gallery/rock-villa/16.jpg",
   "images/gallery/rock-villa/17.jpg",
   "images/gallery/rock-villa/18.jpg",
   "images/gallery/rock-villa/19.jpg",
   "images/gallery/rock-villa/20.jpg"
  ]
 },
 "solar-crab": {
  "name": "Solar Crab",
  "images": [
   "images/gallery/solar-crab/01.jpg",
   "images/gallery/solar-crab/02.jpg",
   "images/gallery/solar-crab/03.jpg",
   "images/gallery/solar-crab/04.jpg",
   "images/gallery/solar-crab/05.jpg",
   "images/gallery/solar-crab/06.jpg",
   "images/gallery/solar-crab/07.jpg",
   "images/gallery/solar-crab/08.jpg",
   "images/gallery/solar-crab/09.jpg",
   "images/gallery/solar-crab/10.jpg",
   "images/gallery/solar-crab/11.jpg",
   "images/gallery/solar-crab/12.jpg",
   "images/gallery/solar-crab/13.jpg"
  ]
 },
 "sun-house": {
  "name": "Sun House",
  "images": [
   "images/gallery/sun-house/01.jpg",
   "images/gallery/sun-house/02.jpg",
   "images/gallery/sun-house/03.jpg",
   "images/gallery/sun-house/04.jpg",
   "images/gallery/sun-house/05.jpg",
   "images/gallery/sun-house/06.jpg",
   "images/gallery/sun-house/07.jpg",
   "images/gallery/sun-house/08.jpg",
   "images/gallery/sun-house/09.jpg",
   "images/gallery/sun-house/10.jpg",
   "images/gallery/sun-house/11.jpg",
   "images/gallery/sun-house/12.jpg",
   "images/gallery/sun-house/13.jpg",
   "images/gallery/sun-house/14.jpg",
   "images/gallery/sun-house/15.jpg"
  ]
 },
 "why-house": {
  "name": "Why House",
  "images": [
   "images/gallery/why-house/01.jpg",
   "images/gallery/why-house/02.jpg",
   "images/gallery/why-house/03.jpg",
   "images/gallery/why-house/04.jpg",
   "images/gallery/why-house/05.jpg",
   "images/gallery/why-house/06.jpg",
   "images/gallery/why-house/07.jpg",
   "images/gallery/why-house/08.jpg",
   "images/gallery/why-house/09.jpg",
   "images/gallery/why-house/10.jpg",
   "images/gallery/why-house/11.jpg",
   "images/gallery/why-house/12.jpg",
   "images/gallery/why-house/13.jpg",
   "images/gallery/why-house/14.jpg",
   "images/gallery/why-house/15.jpg",
   "images/gallery/why-house/16.jpg",
   "images/gallery/why-house/17.jpg",
   "images/gallery/why-house/18.jpg",
   "images/gallery/why-house/19.jpg",
   "images/gallery/why-house/20.jpg",
   "images/gallery/why-house/21.jpg",
   "images/gallery/why-house/22.jpg",
   "images/gallery/why-house/23.jpg",
   "images/gallery/why-house/24.jpg"
  ]
 }
};
