/** Tailwind config — ported 1:1 from the Stitch "Architectural Narrative" design system.
 *  Only deliberate change: font fallback "cursive" -> "sans-serif" (production safety). */
module.exports = {
  content: ["./index.html", "./portfolio.html", "./about.html", "./gallery.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "inverse-on-surface": "#f0f1f1",
        "on-surface": "#0F0F0F",
        "primary-fixed-dim": "#c8c6c5",
        error: "#ba1a1a",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-container": "#e3e2e2",
        "tertiary-container": "#1a1c1c",
        surface: "#f9f9f9",
        "charcoal-deep": "#0F0F0F",
        "on-primary-fixed": "#1c1b1b",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#474746",
        tertiary: "#000000",
        "on-tertiary-fixed": "#1a1c1c",
        "on-secondary-fixed-variant": "#464747",
        "on-tertiary-container": "#838484",
        "on-error-container": "#93000a",
        secondary: "#5e5e5e",
        "surface-variant": "#e2e2e2",
        "surface-container": "#eeeeee",
        "canvas-off-white": "#FAFAFA",
        "on-secondary-fixed": "#1b1c1c",
        "tertiary-fixed": "#e2e2e2",
        "primary-container": "#1c1b1b",
        "secondary-fixed": "#e3e2e2",
        "border-muted": "#E0E0E0",
        "surface-container-highest": "#e2e2e2",
        "surface-tint": "#5f5e5e",
        "on-secondary-container": "#646464",
        background: "#f9f9f9",
        "on-surface-variant": "#444748",
        "surface-container-low": "#f3f3f4",
        "on-secondary": "#ffffff",
        "surface-dim": "#dadada",
        outline: "#747878",
        "on-tertiary-fixed-variant": "#454747",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-container-high": "#e8e8e8",
        "inverse-surface": "#2f3131",
        "primary-fixed": "#e5e2e1",
        primary: "#000000",
        "on-background": "#1a1c1c",
        "glass-overlay": "rgba(255, 255, 255, 0.9)",
        "on-primary-container": "#858383",
        "secondary-fixed-dim": "#c7c6c6",
        "outline-variant": "#c4c7c7",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#c8c6c5",
        "surface-bright": "#f9f9f9",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "container-max": "1440px",
        "margin-tablet": "40px",
        "section-gap": "160px",
        "margin-desktop": "80px",
        gutter: "32px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        sans: ["Poiret One", "sans-serif"],
        serif: ["Poiret One", "sans-serif"],
        display: ["Poiret One", "sans-serif"],
        body: ["Poiret One", "sans-serif"],
        label: ["Poiret One", "sans-serif"],
        quote: ["Poiret One", "sans-serif"],
        "body-md": ["Poiret One", "sans-serif"],
        "display-lg": ["Poiret One", "sans-serif"],
        "body-lg": ["Poiret One", "sans-serif"],
        "headline-sm": ["Poiret One", "sans-serif"],
        "label-caps": ["Poiret One", "sans-serif"],
        "headline-md": ["Poiret One", "sans-serif"],
        "display-lg-mobile": ["Poiret One", "sans-serif"],
      },
      fontSize: {
        quote: ["24px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.8", fontWeight: "400" }],
        "display-lg": ["72px", { lineHeight: "1.05", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-lg": ["20px", { lineHeight: "1.8", fontWeight: "400" }],
        "headline-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0.15em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.25em", fontWeight: "700" }],
        "headline-md": ["40px", { lineHeight: "1.2", fontWeight: "400" }],
        "display-lg-mobile": ["48px", { lineHeight: "1.1", letterSpacing: "-0.01em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
